[2025-01-11T13:25:28.551+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-11T13:25:28.667+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dynamic_task_mapping_with_fixed_chunk_size_operator.process_chunk manual__2025-01-11T13:25:18.459655+00:00 map_index=4 [queued]>
[2025-01-11T13:25:28.719+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dynamic_task_mapping_with_fixed_chunk_size_operator.process_chunk manual__2025-01-11T13:25:18.459655+00:00 map_index=4 [queued]>
[2025-01-11T13:25:28.720+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-11T13:25:28.927+0000] {taskinstance.py:2889} INFO - Executing <Mapped(PythonOperator): process_chunk> on 2025-01-11 13:25:18.459655+00:00
[2025-01-11T13:25:28.978+0000] {standard_task_runner.py:72} INFO - Started process 1272 to run task
[2025-01-11T13:25:29.172+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dynamic_task_mapping_with_fixed_chunk_size_operator', 'process_chunk', 'manual__2025-01-11T13:25:18.459655+00:00', '--job-id', '835', '--raw', '--subdir', 'DAGS_FOLDER/experiments/dynamic_task_mapping_sequentials.py', '--cfg-path', '/tmp/tmpc67yp0zs', '--map-index', '4']
[2025-01-11T13:25:29.187+0000] {standard_task_runner.py:105} INFO - Job 835: Subtask process_chunk
[2025-01-11T13:25:29.728+0000] {task_command.py:467} INFO - Running <TaskInstance: dynamic_task_mapping_with_fixed_chunk_size_operator.process_chunk manual__2025-01-11T13:25:18.459655+00:00 map_index=4 [running]> on host 02aab7e5da88
[2025-01-11T13:25:30.389+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dynamic_task_mapping_with_fixed_chunk_size_operator' AIRFLOW_CTX_TASK_ID='process_chunk' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T13:25:18.459655+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-11T13:25:18.459655+00:00'
[2025-01-11T13:25:30.415+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-11T13:25:30.444+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
TypeError: process_chunk() takes 1 positional argument but 100000 were given
[2025-01-11T13:25:30.452+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dynamic_task_mapping_with_fixed_chunk_size_operator, task_id=process_chunk, run_id=manual__2025-01-11T13:25:18.459655+00:00, map_index=4, execution_date=20250111T132518, start_date=20250111T132528, end_date=20250111T132530
[2025-01-11T13:25:30.460+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-11T13:25:30.461+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 835 for task process_chunk (process_chunk() takes 1 positional argument but 100000 were given; 1272)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
TypeError: process_chunk() takes 1 positional argument but 100000 were given
[2025-01-11T13:25:30.495+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-11T13:25:30.546+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-11T13:25:30.547+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
