[2025-01-11T11:53:45.454+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-11T11:53:45.462+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dynamic_task_mapping_sequentials_dag.generate_task manual__2025-01-11T11:53:41.385829+00:00 [queued]>
[2025-01-11T11:53:45.468+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dynamic_task_mapping_sequentials_dag.generate_task manual__2025-01-11T11:53:41.385829+00:00 [queued]>
[2025-01-11T11:53:45.468+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-11T11:53:45.477+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_task> on 2025-01-11 11:53:41.385829+00:00
[2025-01-11T11:53:45.483+0000] {standard_task_runner.py:72} INFO - Started process 146 to run task
[2025-01-11T11:53:45.487+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dynamic_task_mapping_sequentials_dag', 'generate_task', 'manual__2025-01-11T11:53:41.385829+00:00', '--job-id', '740', '--raw', '--subdir', 'DAGS_FOLDER/experiments/dynamic_task_mapping_sequentials_dag.py', '--cfg-path', '/tmp/tmp9c1m11op']
[2025-01-11T11:53:45.490+0000] {standard_task_runner.py:105} INFO - Job 740: Subtask generate_task
[2025-01-11T11:53:45.528+0000] {task_command.py:467} INFO - Running <TaskInstance: dynamic_task_mapping_sequentials_dag.generate_task manual__2025-01-11T11:53:41.385829+00:00 [running]> on host a2978c5b6b3a
[2025-01-11T11:53:45.562+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dynamic_task_mapping_sequentials_dag' AIRFLOW_CTX_TASK_ID='generate_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T11:53:41.385829+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-11T11:53:41.385829+00:00'
[2025-01-11T11:53:45.562+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-11T11:53:46.132+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-11T11:53:46.142+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-11T11:53:46.143+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dynamic_task_mapping_sequentials_dag, task_id=generate_task, run_id=manual__2025-01-11T11:53:41.385829+00:00, execution_date=20250111T115341, start_date=20250111T115345, end_date=20250111T115346
[2025-01-11T11:53:46.161+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-11T11:53:46.172+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-11T11:53:46.172+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
