[2025-01-11T13:07:59.888+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-11T13:07:59.948+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dynamic_task_mapping_with_fixed_chunk_size.fetch_data manual__2025-01-11T13:07:58.190134+00:00 [queued]>
[2025-01-11T13:07:59.984+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dynamic_task_mapping_with_fixed_chunk_size.fetch_data manual__2025-01-11T13:07:58.190134+00:00 [queued]>
[2025-01-11T13:07:59.986+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-11T13:08:00.038+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_data> on 2025-01-11 13:07:58.190134+00:00
[2025-01-11T13:08:00.052+0000] {standard_task_runner.py:72} INFO - Started process 971 to run task
[2025-01-11T13:08:00.058+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dynamic_task_mapping_with_fixed_chunk_size', 'fetch_data', 'manual__2025-01-11T13:07:58.190134+00:00', '--job-id', '811', '--raw', '--subdir', 'DAGS_FOLDER/experiments/dynamic_task_mapping_sequentials.py', '--cfg-path', '/tmp/tmpfn05oan_']
[2025-01-11T13:08:00.061+0000] {standard_task_runner.py:105} INFO - Job 811: Subtask fetch_data
[2025-01-11T13:08:00.242+0000] {task_command.py:467} INFO - Running <TaskInstance: dynamic_task_mapping_with_fixed_chunk_size.fetch_data manual__2025-01-11T13:07:58.190134+00:00 [running]> on host 02aab7e5da88
[2025-01-11T13:08:00.810+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dynamic_task_mapping_with_fixed_chunk_size' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T13:07:58.190134+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-11T13:07:58.190134+00:00'
[2025-01-11T13:08:00.823+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-11T13:08:01.186+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-11T13:08:01.198+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-11T13:08:01.198+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dynamic_task_mapping_with_fixed_chunk_size, task_id=fetch_data, run_id=manual__2025-01-11T13:07:58.190134+00:00, execution_date=20250111T130758, start_date=20250111T130759, end_date=20250111T130801
[2025-01-11T13:08:01.236+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-11T13:08:01.278+0000] {dagrun.py:977} ERROR - Failed to get task for ti <TaskInstance: dynamic_task_mapping_with_fixed_chunk_size.process_data manual__2025-01-11T13:07:58.190134+00:00 [None]>. Marking it as removed.
[2025-01-11T13:08:01.283+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-11T13:08:01.284+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
